// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir/gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{prelude::*,signal::{connect_raw, SignalHandlerId},translate::*};
use std::{boxed::Box as Box_};

glib::wrapper! {
    #[doc(alias = "AstalBox")]
    pub struct Box(Object<ffi::AstalBox, ffi::AstalBoxClass>) @extends gtk::Box, gtk::Container, gtk::Widget, gobject::InitiallyUnowned, @implements atk::ImplementorIface, gtk::Buildable, gtk::Orientable;

    match fn {
        type_ => || ffi::astal_box_get_type(),
    }
}

impl Box {
        pub const NONE: Option<&'static Box> = None;
    

    #[doc(alias = "astal_box_new")]
    pub fn new(vertical: bool, children: &[gtk::Widget]) -> Box {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_none(ffi::astal_box_new(vertical.into_glib(), children.to_glib_none().0))
        }
    }
}

pub trait BoxExt: IsA<Box> + 'static {
    #[doc(alias = "astal_box_get_vertical")]
    #[doc(alias = "get_vertical")]
    fn is_vertical(&self) -> bool {
        unsafe {
            from_glib(ffi::astal_box_get_vertical(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_box_set_vertical")]
    fn set_vertical(&self, value: bool) {
        unsafe {
            ffi::astal_box_set_vertical(self.as_ref().to_glib_none().0, value.into_glib());
        }
    }

    #[doc(alias = "astal_box_get_children")]
    #[doc(alias = "get_children")]
    fn children(&self) -> Vec<gtk::Widget> {
        unsafe {
            FromGlibPtrContainer::from_glib_container(ffi::astal_box_get_children(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_box_set_children")]
    fn set_children(&self, value: &[gtk::Widget]) {
        unsafe {
            ffi::astal_box_set_children(self.as_ref().to_glib_none().0, value.to_glib_none().0);
        }
    }

    #[doc(alias = "astal_box_get_child")]
    #[doc(alias = "get_child")]
    fn child(&self) -> Option<gtk::Widget> {
        unsafe {
            from_glib_full(ffi::astal_box_get_child(self.as_ref().to_glib_none().0))
        }
    }

    #[doc(alias = "astal_box_set_child")]
    fn set_child(&self, value: &impl IsA<gtk::Widget>) {
        unsafe {
            ffi::astal_box_set_child(self.as_ref().to_glib_none().0, value.as_ref().to_glib_none().0);
        }
    }

    #[doc(alias = "vertical")]
    fn connect_vertical_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_vertical_trampoline<P: IsA<Box>, F: Fn(&P) + 'static>(this: *mut ffi::AstalBox, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Box::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::vertical\0".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_vertical_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }

    #[doc(alias = "children")]
    fn connect_children_notify<F: Fn(&Self) + 'static>(&self, f: F) -> SignalHandlerId {
        unsafe extern "C" fn notify_children_trampoline<P: IsA<Box>, F: Fn(&P) + 'static>(this: *mut ffi::AstalBox, _param_spec: glib::ffi::gpointer, f: glib::ffi::gpointer) {
            let f: &F = &*(f as *const F);
            f(Box::from_glib_borrow(this).unsafe_cast_ref())
        }
        unsafe {
            let f: Box_<F> = Box_::new(f);
            connect_raw(self.as_ptr() as *mut _, b"notify::children\0".as_ptr() as *const _,
                Some(std::mem::transmute::<*const (), unsafe extern "C" fn()>(notify_children_trampoline::<Self, F> as *const ())), Box_::into_raw(f))
        }
    }
}

impl<O: IsA<Box>> BoxExt for O {}
