// Generated by gir (https://github.com/gtk-rs/gir @ 26e721588f2f)
// from ../../gir/gir-files (@ e02639f55a90)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalAuthPamClass", sizeof(AstalAuthPamClass), alignof(AstalAuthPamClass));
    return 0;
}
