// Generated by gir (https://github.com/gtk-rs/gir @ 88259bc5f36f+)
// from ../../gir/gir-files (@ 1783d05ebac3+)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalNotifdAction", sizeof(AstalNotifdAction), alignof(AstalNotifdAction));
    printf("%s;%zu;%zu\n", "AstalNotifdClosedReason", sizeof(AstalNotifdClosedReason), alignof(AstalNotifdClosedReason));
    printf("%s;%zu;%zu\n", "AstalNotifdNotifd", sizeof(AstalNotifdNotifd), alignof(AstalNotifdNotifd));
    printf("%s;%zu;%zu\n", "AstalNotifdNotifdClass", sizeof(AstalNotifdNotifdClass), alignof(AstalNotifdNotifdClass));
    printf("%s;%zu;%zu\n", "AstalNotifdNotification", sizeof(AstalNotifdNotification), alignof(AstalNotifdNotification));
    printf("%s;%zu;%zu\n", "AstalNotifdNotificationClass", sizeof(AstalNotifdNotificationClass), alignof(AstalNotifdNotificationClass));
    printf("%s;%zu;%zu\n", "AstalNotifdUrgency", sizeof(AstalNotifdUrgency), alignof(AstalNotifdUrgency));
    return 0;
}
