// Generated by gir (https://github.com/gtk-rs/gir @ 88259bc5f36f+)
// from ../../gir/gir-files (@ 1783d05ebac3+)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalRiverOutputClass", sizeof(AstalRiverOutputClass), alignof(AstalRiverOutputClass));
    printf("%s;%zu;%zu\n", "AstalRiverRiverClass", sizeof(AstalRiverRiverClass), alignof(AstalRiverRiverClass));
    return 0;
}
