// Generated by gir (https://github.com/gtk-rs/gir @ 0cdde9fbfd9d)
// from ../../gir/gir-files (@ e6660f4e9430+)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalRiverOutputClass", sizeof(AstalRiverOutputClass), alignof(AstalRiverOutputClass));
    printf("%s;%zu;%zu\n", "AstalRiverRiverClass", sizeof(AstalRiverRiverClass), alignof(AstalRiverRiverClass));
    return 0;
}
