[options]
library = "Astal"
version = "3.0"
min_cfg_version = "1.0"
target_path = "."
girs_directories = ["../../gir/gir-files"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
	"Astal.MouseButton",
	"Astal.WindowAnchor",
	"Astal.Exclusivity",
	"Astal.Layer",
	"Astal.Keymode",
	"Astal.Button",
	"Astal.HoverEvent",
	"Astal.ClickEvent",
	"Astal.ScrollEvent",
	"Astal.EventBox",
	"Astal.MotionEvent",
	"Astal.*",
]

manual = [
	"Gtk.Widget",
	"Gtk.Box",
	"Gtk.Container",
	"GObject.InitiallyUnowned",
	"Atk.ImplementorIface",
	"Gtk.Orientable",
	"Gtk.Button",
	"Gtk.Buildable",
	"Gtk.Bin",
	"Gtk.Actionable",
	"Gtk.Activatable",
	"Gtk.EventBox",
	"Gtk.Image",
	"Gtk.Misc",
	"Gtk.Label",
	"Gtk.LevelBar",
	"Gtk.Overlay",
	"Gtk.ScrolledWindow",
	"Gtk.Scale",
	"Gtk.Range",
	"Gtk.Stack",
	"Gtk.Window",
	"Gtk.Application",
	"Gio.Application",
	"Gio.ActionGroup",
	"Gio.ActionMap",
	"Gdk.Monitor",
	"Gtk.PolicyType",
	"Gio.Icon",
	"Gtk.IconInfo",
	"GdkPixbuf.Pixbuf",
	"AstalIO.Application",
	"Gio.SocketConnection",
	"Gdk.EventCrossing",
	"Gdk.EventButton",
	"Gdk.EventScroll",
	"Gdk.EventMotion",
	"Gtk.ResizeMode",
	"Gtk.BaselinePosition",
	"Gio.MenuModel",
	"Gio.ApplicationFlags",
	"Gdk.EventMask",
	"Gtk.Align",
	"Gtk.Style",
	"Gtk.Orientation",
	"cairo.Surface",
	"Gtk.IconSize",
	"GdkPixbuf.PixbufAnimation",
	"Pango.AttrList",
	"Pango.EllipsizeMode",
	"Gtk.Justification",
	"Gtk.LevelBarMode",
	"Gtk.Adjustment",
	"Gtk.ShadowType",
	"Gtk.CornerType",
	"Gtk.PositionType",
	"Gtk.SensitivityType",
	"Gtk.StackTransitionType",
	"Gdk.Gravity",
	"Gdk.Screen",
	"Gtk.WindowType",
	"Gdk.WindowTypeHint",
	"Gtk.WindowPosition",
	"Pango.WrapMode",
]

# gtk doesn't generate some object right
ignore = ["Gtk.IconSet"]

[[object]]
name = "Astal.Box"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.CenterBox"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.CircularProgress"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.Icon"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.Label"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.LevelBar"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.Overlay"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.Scrollable"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.Slider"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.Stack"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.Window"
status = "generate"
generate_builder = true
[[object]]
name = "Astal.Application"
status = "generate"
generate_builder = true
