[options]
library = "AstalIO"
version = "0.1"
min_cfg_version = "0.1"
target_path = "."
girs_directories = ["../../gir/gir-files"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
	"AstalIO.AppError",
	"AstalIO.Time",
	"AstalIO.VariableBase",
	"AstalIO.Application",
	"AstalIO.*",
]

manual = [
	"GLib.Error",
	"Gio.AsyncReadyCallback",
	"Gio.AsyncResult",
	"GObject.Closure",
	"GObject.Value",
	"Gio.SocketConnection",
	"Gio.SocketService",
	"Gio.FileMonitor",
]

[[object]]
name = "AstalIO.Process"
status = "generate"
generate_builder = true

[[object]]
name = "AstalIO.Variable"
status = "generate"
generate_builder = true
