// Generated by gir (https://github.com/gtk-rs/gir @ 0cdde9fbfd9d)
// from /usr/share/gir-1.0 (@ ???)
// from ../../../gobject/gir-files (@ ???)
// DO NOT EDIT

#[cfg(not(docsrs))]
use std::process;

#[cfg(docsrs)]
fn main() {} // prevent linking libraries to avoid documentation failure

#[cfg(not(docsrs))]
fn main() {
    if let Err(s) = system_deps::Config::new().probe() {
        println!("cargo:warning={s}");
        process::exit(1);
    }
}
