[options]
library = "AstalPowerProfiles"
version = "0.1"
min_cfg_version = "0.1"
target_path = "."
girs_directories = ["../../gir/gir-files"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = ["AstalPowerProfiles.Hold", "AstalPowerProfiles.Profile"]

manual = []

[[object]]
name = "AstalPowerProfiles.PowerProfiles"
status = "generate"
generate_builder = true
