// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir/gir-files
// DO NOT EDIT

mod pam;
pub use self::pam::Pam;

pub mod builders {
    pub use super::pam::PamBuilder;
}
