[options]
library = "AstalNotifd"
version = "0.1"
min_cfg_version = "0.1"
target_path = "."
girs_directories = ["../../gir/gir-files"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
    "AstalNotifd.ClosedReason",
    "AstalNotifd.Urgency",
    "AstalNotifd.Action",
]

manual = ["GLib.Variant"]

[[object]]
name = "AstalNotifd.Notifd"
status = "generate"
generate_builder = true

[[object]]
name = "AstalNotifd.Notification"
status = "generate"
generate_builder = true
