// Generated by gir (https://github.com/gtk-rs/gir @ 58beae1b3c03+)
// from ../../gir/gir-files (@ d520e1e8fcc5+)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalApplication", sizeof(AstalApplication), alignof(AstalApplication));
    printf("%s;%zu;%zu\n", "AstalApplicationClass", sizeof(AstalApplicationClass), alignof(AstalApplicationClass));
    printf("%s;%zu;%zu\n", "AstalBox", sizeof(AstalBox), alignof(AstalBox));
    printf("%s;%zu;%zu\n", "AstalBoxClass", sizeof(AstalBoxClass), alignof(AstalBoxClass));
    printf("%s;%zu;%zu\n", "AstalButton", sizeof(AstalButton), alignof(AstalButton));
    printf("%s;%zu;%zu\n", "AstalButtonClass", sizeof(AstalButtonClass), alignof(AstalButtonClass));
    printf("%s;%zu;%zu\n", "AstalCenterBox", sizeof(AstalCenterBox), alignof(AstalCenterBox));
    printf("%s;%zu;%zu\n", "AstalCenterBoxClass", sizeof(AstalCenterBoxClass), alignof(AstalCenterBoxClass));
    printf("%s;%zu;%zu\n", "AstalCircularProgress", sizeof(AstalCircularProgress), alignof(AstalCircularProgress));
    printf("%s;%zu;%zu\n", "AstalCircularProgressClass", sizeof(AstalCircularProgressClass), alignof(AstalCircularProgressClass));
    printf("%s;%zu;%zu\n", "AstalClickEvent", sizeof(AstalClickEvent), alignof(AstalClickEvent));
    printf("%s;%zu;%zu\n", "AstalEventBox", sizeof(AstalEventBox), alignof(AstalEventBox));
    printf("%s;%zu;%zu\n", "AstalEventBoxClass", sizeof(AstalEventBoxClass), alignof(AstalEventBoxClass));
    printf("%s;%zu;%zu\n", "AstalExclusivity", sizeof(AstalExclusivity), alignof(AstalExclusivity));
    printf("%s;%zu;%zu\n", "AstalHoverEvent", sizeof(AstalHoverEvent), alignof(AstalHoverEvent));
    printf("%s;%zu;%zu\n", "AstalIcon", sizeof(AstalIcon), alignof(AstalIcon));
    printf("%s;%zu;%zu\n", "AstalIconClass", sizeof(AstalIconClass), alignof(AstalIconClass));
    printf("%s;%zu;%zu\n", "AstalKeymode", sizeof(AstalKeymode), alignof(AstalKeymode));
    printf("%s;%zu;%zu\n", "AstalLabel", sizeof(AstalLabel), alignof(AstalLabel));
    printf("%s;%zu;%zu\n", "AstalLabelClass", sizeof(AstalLabelClass), alignof(AstalLabelClass));
    printf("%s;%zu;%zu\n", "AstalLayer", sizeof(AstalLayer), alignof(AstalLayer));
    printf("%s;%zu;%zu\n", "AstalLevelBar", sizeof(AstalLevelBar), alignof(AstalLevelBar));
    printf("%s;%zu;%zu\n", "AstalLevelBarClass", sizeof(AstalLevelBarClass), alignof(AstalLevelBarClass));
    printf("%s;%zu;%zu\n", "AstalMotionEvent", sizeof(AstalMotionEvent), alignof(AstalMotionEvent));
    printf("%s;%zu;%zu\n", "AstalMouseButton", sizeof(AstalMouseButton), alignof(AstalMouseButton));
    printf("%s;%zu;%zu\n", "AstalOverlay", sizeof(AstalOverlay), alignof(AstalOverlay));
    printf("%s;%zu;%zu\n", "AstalOverlayClass", sizeof(AstalOverlayClass), alignof(AstalOverlayClass));
    printf("%s;%zu;%zu\n", "AstalScrollEvent", sizeof(AstalScrollEvent), alignof(AstalScrollEvent));
    printf("%s;%zu;%zu\n", "AstalScrollable", sizeof(AstalScrollable), alignof(AstalScrollable));
    printf("%s;%zu;%zu\n", "AstalScrollableClass", sizeof(AstalScrollableClass), alignof(AstalScrollableClass));
    printf("%s;%zu;%zu\n", "AstalSlider", sizeof(AstalSlider), alignof(AstalSlider));
    printf("%s;%zu;%zu\n", "AstalSliderClass", sizeof(AstalSliderClass), alignof(AstalSliderClass));
    printf("%s;%zu;%zu\n", "AstalStack", sizeof(AstalStack), alignof(AstalStack));
    printf("%s;%zu;%zu\n", "AstalStackClass", sizeof(AstalStackClass), alignof(AstalStackClass));
    printf("%s;%zu;%zu\n", "AstalWindow", sizeof(AstalWindow), alignof(AstalWindow));
    printf("%s;%zu;%zu\n", "AstalWindowAnchor", sizeof(AstalWindowAnchor), alignof(AstalWindowAnchor));
    printf("%s;%zu;%zu\n", "AstalWindowClass", sizeof(AstalWindowClass), alignof(AstalWindowClass));
    return 0;
}
