// Generated by gir (https://github.com/gtk-rs/gir @ 74c0d5542b5c)
// from ../../gir/gir-files (@ 1783d05ebac3+)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalMprisLoop", sizeof(AstalMprisLoop), alignof(AstalMprisLoop));
    printf("%s;%zu;%zu\n", "AstalMprisMpris", sizeof(AstalMprisMpris), alignof(AstalMprisMpris));
    printf("%s;%zu;%zu\n", "AstalMprisMprisClass", sizeof(AstalMprisMprisClass), alignof(AstalMprisMprisClass));
    printf("%s;%zu;%zu\n", "AstalMprisPlaybackStatus", sizeof(AstalMprisPlaybackStatus), alignof(AstalMprisPlaybackStatus));
    printf("%s;%zu;%zu\n", "AstalMprisPlayer", sizeof(AstalMprisPlayer), alignof(AstalMprisPlayer));
    printf("%s;%zu;%zu\n", "AstalMprisPlayerClass", sizeof(AstalMprisPlayerClass), alignof(AstalMprisPlayerClass));
    printf("%s;%zu;%zu\n", "AstalMprisShuffle", sizeof(AstalMprisShuffle), alignof(AstalMprisShuffle));
    return 0;
}
