[package]
name = "gnyprland"
version = "0.1.0"
edition = "2021"
default-run = "gnyprland"

[dependencies.astal]
path = "../astal"

[dependencies.gtk]
git = "https://github.com/onlycs/gtk3-rs"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs-core"
