// Generated by gir (https://github.com/gtk-rs/gir @ 0cdde9fbfd9d)
// from ../../gir/gir-files (@ e6660f4e9430+)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalPowerProfilesHold", sizeof(AstalPowerProfilesHold), alignof(AstalPowerProfilesHold));
    printf("%s;%zu;%zu\n", "AstalPowerProfilesPowerProfiles", sizeof(AstalPowerProfilesPowerProfiles), alignof(AstalPowerProfilesPowerProfiles));
    printf("%s;%zu;%zu\n", "AstalPowerProfilesPowerProfilesClass", sizeof(AstalPowerProfilesPowerProfilesClass), alignof(AstalPowerProfilesPowerProfilesClass));
    printf("%s;%zu;%zu\n", "AstalPowerProfilesProfile", sizeof(AstalPowerProfilesProfile), alignof(AstalPowerProfilesProfile));
    return 0;
}
