// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir/gir-files
// DO NOT EDIT

#![cfg(unix)]

use astal_sys::*;
use std::mem::{align_of, size_of};
use std::env;
use std::error::Error;
use std::ffi::OsString;
use std::path::Path;
use std::process::{Command, Stdio};
use std::str;
use tempfile::Builder;

static PACKAGES: &[&str] = &["astal"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Self, Box<dyn Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        // For _Generic
        args.push("-std=c11".to_owned());
        // For %z support in printf when using MinGW.
        args.push("-D__USE_MINGW_ANSI_STDIO".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Self { args })
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {cmd:?} failed, {status}").into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<dyn Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{name} {err}").into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<dyn Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let pkg_config = env::var_os("PKG_CONFIG")
        .unwrap_or_else(|| OsString::from("pkg-config"));
    let mut cmd = Command::new(pkg_config);
    cmd.arg("--cflags");
    cmd.args(packages);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}


#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn summary(&self) -> String {
        format!("{} passed; {} failed", self.passed, self.failed)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let mut c_constants: Vec<(String, String)> = Vec::new();

    for l in get_c_output("constant").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing ';' separator");
        c_constants.push((name.to_owned(), value.to_owned()));
    }

    let mut results = Results::default();

    for ((rust_name, rust_value), (c_name, c_value)) in
        RUST_CONSTANTS.iter().zip(c_constants.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_value != c_value {
            results.record_failed();
            eprintln!(
                "Constant value mismatch for {rust_name}\nRust: {rust_value:?}\nC:    {c_value:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let mut c_layouts = Vec::new();

    for l in get_c_output("layout").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing first ';' separator");
        let (size, alignment) = value.split_once(';').expect("Missing second ';' separator");
        let size = size.parse().expect("Failed to parse size");
        let alignment = alignment.parse().expect("Failed to parse alignment");
        c_layouts.push((name.to_owned(), Layout { size, alignment }));
    }

    let mut results = Results::default();

    for ((rust_name, rust_layout), (c_name, c_layout)) in
        RUST_LAYOUTS.iter().zip(c_layouts.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_layout != c_layout {
            results.record_failed();
            eprintln!(
                "Layout mismatch for {rust_name}\nRust: {rust_layout:?}\nC:    {c_layout:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

fn get_c_output(name: &str) -> Result<String, Box<dyn Error>> {
    let tmpdir = Builder::new().prefix("abi").tempdir()?;
    let exe = tmpdir.path().join(name);
    let c_file = Path::new("tests").join(name).with_extension("c");

    let cc = Compiler::new().expect("configured compiler");
    cc.compile(&c_file, &exe)?;

    let mut cmd = Command::new(exe);
    cmd.stderr(Stdio::inherit());
    let out = cmd.output()?;
    if !out.status.success() {
        let (status, stdout) = (out.status, String::from_utf8_lossy(&out.stdout));
        return Err(format!("command {cmd:?} failed, {status:?}\nstdout: {stdout}").into());
    }

    Ok(String::from_utf8(out.stdout)?)
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    ("AstalApplication", Layout {size: size_of::<AstalApplication>(), alignment: align_of::<AstalApplication>()}),
    ("AstalApplicationClass", Layout {size: size_of::<AstalApplicationClass>(), alignment: align_of::<AstalApplicationClass>()}),
    ("AstalBox", Layout {size: size_of::<AstalBox>(), alignment: align_of::<AstalBox>()}),
    ("AstalBoxClass", Layout {size: size_of::<AstalBoxClass>(), alignment: align_of::<AstalBoxClass>()}),
    ("AstalButton", Layout {size: size_of::<AstalButton>(), alignment: align_of::<AstalButton>()}),
    ("AstalButtonClass", Layout {size: size_of::<AstalButtonClass>(), alignment: align_of::<AstalButtonClass>()}),
    ("AstalCenterBox", Layout {size: size_of::<AstalCenterBox>(), alignment: align_of::<AstalCenterBox>()}),
    ("AstalCenterBoxClass", Layout {size: size_of::<AstalCenterBoxClass>(), alignment: align_of::<AstalCenterBoxClass>()}),
    ("AstalCircularProgress", Layout {size: size_of::<AstalCircularProgress>(), alignment: align_of::<AstalCircularProgress>()}),
    ("AstalCircularProgressClass", Layout {size: size_of::<AstalCircularProgressClass>(), alignment: align_of::<AstalCircularProgressClass>()}),
    ("AstalClickEvent", Layout {size: size_of::<AstalClickEvent>(), alignment: align_of::<AstalClickEvent>()}),
    ("AstalEventBox", Layout {size: size_of::<AstalEventBox>(), alignment: align_of::<AstalEventBox>()}),
    ("AstalEventBoxClass", Layout {size: size_of::<AstalEventBoxClass>(), alignment: align_of::<AstalEventBoxClass>()}),
    ("AstalExclusivity", Layout {size: size_of::<AstalExclusivity>(), alignment: align_of::<AstalExclusivity>()}),
    ("AstalHoverEvent", Layout {size: size_of::<AstalHoverEvent>(), alignment: align_of::<AstalHoverEvent>()}),
    ("AstalIcon", Layout {size: size_of::<AstalIcon>(), alignment: align_of::<AstalIcon>()}),
    ("AstalIconClass", Layout {size: size_of::<AstalIconClass>(), alignment: align_of::<AstalIconClass>()}),
    ("AstalKeymode", Layout {size: size_of::<AstalKeymode>(), alignment: align_of::<AstalKeymode>()}),
    ("AstalLabel", Layout {size: size_of::<AstalLabel>(), alignment: align_of::<AstalLabel>()}),
    ("AstalLabelClass", Layout {size: size_of::<AstalLabelClass>(), alignment: align_of::<AstalLabelClass>()}),
    ("AstalLayer", Layout {size: size_of::<AstalLayer>(), alignment: align_of::<AstalLayer>()}),
    ("AstalLevelBar", Layout {size: size_of::<AstalLevelBar>(), alignment: align_of::<AstalLevelBar>()}),
    ("AstalLevelBarClass", Layout {size: size_of::<AstalLevelBarClass>(), alignment: align_of::<AstalLevelBarClass>()}),
    ("AstalMotionEvent", Layout {size: size_of::<AstalMotionEvent>(), alignment: align_of::<AstalMotionEvent>()}),
    ("AstalMouseButton", Layout {size: size_of::<AstalMouseButton>(), alignment: align_of::<AstalMouseButton>()}),
    ("AstalOverlay", Layout {size: size_of::<AstalOverlay>(), alignment: align_of::<AstalOverlay>()}),
    ("AstalOverlayClass", Layout {size: size_of::<AstalOverlayClass>(), alignment: align_of::<AstalOverlayClass>()}),
    ("AstalScrollEvent", Layout {size: size_of::<AstalScrollEvent>(), alignment: align_of::<AstalScrollEvent>()}),
    ("AstalScrollable", Layout {size: size_of::<AstalScrollable>(), alignment: align_of::<AstalScrollable>()}),
    ("AstalScrollableClass", Layout {size: size_of::<AstalScrollableClass>(), alignment: align_of::<AstalScrollableClass>()}),
    ("AstalSlider", Layout {size: size_of::<AstalSlider>(), alignment: align_of::<AstalSlider>()}),
    ("AstalSliderClass", Layout {size: size_of::<AstalSliderClass>(), alignment: align_of::<AstalSliderClass>()}),
    ("AstalStack", Layout {size: size_of::<AstalStack>(), alignment: align_of::<AstalStack>()}),
    ("AstalStackClass", Layout {size: size_of::<AstalStackClass>(), alignment: align_of::<AstalStackClass>()}),
    ("AstalWindow", Layout {size: size_of::<AstalWindow>(), alignment: align_of::<AstalWindow>()}),
    ("AstalWindowAnchor", Layout {size: size_of::<AstalWindowAnchor>(), alignment: align_of::<AstalWindowAnchor>()}),
    ("AstalWindowClass", Layout {size: size_of::<AstalWindowClass>(), alignment: align_of::<AstalWindowClass>()}),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("(gint) ASTAL_EXCLUSIVITY_EXCLUSIVE", "1"),
    ("(gint) ASTAL_EXCLUSIVITY_IGNORE", "2"),
    ("(gint) ASTAL_EXCLUSIVITY_NORMAL", "0"),
    ("(gint) ASTAL_KEYMODE_EXCLUSIVE", "1"),
    ("(gint) ASTAL_KEYMODE_NONE", "0"),
    ("(gint) ASTAL_KEYMODE_ON_DEMAND", "2"),
    ("(gint) ASTAL_LAYER_BACKGROUND", "0"),
    ("(gint) ASTAL_LAYER_BOTTOM", "1"),
    ("(gint) ASTAL_LAYER_OVERLAY", "3"),
    ("(gint) ASTAL_LAYER_TOP", "2"),
    ("ASTAL_MAJOR_VERSION", "3"),
    ("ASTAL_MICRO_VERSION", "0"),
    ("ASTAL_MINOR_VERSION", "0"),
    ("(gint) ASTAL_MOUSE_BUTTON_BACK", "4"),
    ("(gint) ASTAL_MOUSE_BUTTON_FORWARD", "5"),
    ("(gint) ASTAL_MOUSE_BUTTON_MIDDLE", "2"),
    ("(gint) ASTAL_MOUSE_BUTTON_PRIMARY", "1"),
    ("(gint) ASTAL_MOUSE_BUTTON_SECONDARY", "3"),
    ("ASTAL_VERSION", "3.0.0"),
    ("(gint) ASTAL_WINDOW_ANCHOR_BOTTOM", "8"),
    ("(gint) ASTAL_WINDOW_ANCHOR_LEFT", "4"),
    ("(gint) ASTAL_WINDOW_ANCHOR_NONE", "0"),
    ("(gint) ASTAL_WINDOW_ANCHOR_RIGHT", "2"),
    ("(gint) ASTAL_WINDOW_ANCHOR_TOP", "1"),
];


