// Generated by gir (https://github.com/gtk-rs/gir @ 26e721588f2f)
// from ../../gir/gir-files (@ e02639f55a90)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalAppsApplication", sizeof(AstalAppsApplication), alignof(AstalAppsApplication));
    printf("%s;%zu;%zu\n", "AstalAppsApplicationClass", sizeof(AstalAppsApplicationClass), alignof(AstalAppsApplicationClass));
    printf("%s;%zu;%zu\n", "AstalAppsApps", sizeof(AstalAppsApps), alignof(AstalAppsApps));
    printf("%s;%zu;%zu\n", "AstalAppsAppsClass", sizeof(AstalAppsAppsClass), alignof(AstalAppsAppsClass));
    printf("%s;%zu;%zu\n", "AstalAppsScore", sizeof(AstalAppsScore), alignof(AstalAppsScore));
    return 0;
}
