// Generated by gir (https://github.com/gtk-rs/gir @ ef4c0819a702+)
// from ../../gir/gir-files (@ b1d701d3273a+)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalBluetoothAdapter", sizeof(AstalBluetoothAdapter), alignof(AstalBluetoothAdapter));
    printf("%s;%zu;%zu\n", "AstalBluetoothAdapterClass", sizeof(AstalBluetoothAdapterClass), alignof(AstalBluetoothAdapterClass));
    printf("%s;%zu;%zu\n", "AstalBluetoothBluetooth", sizeof(AstalBluetoothBluetooth), alignof(AstalBluetoothBluetooth));
    printf("%s;%zu;%zu\n", "AstalBluetoothBluetoothClass", sizeof(AstalBluetoothBluetoothClass), alignof(AstalBluetoothBluetoothClass));
    printf("%s;%zu;%zu\n", "AstalBluetoothDevice", sizeof(AstalBluetoothDevice), alignof(AstalBluetoothDevice));
    printf("%s;%zu;%zu\n", "AstalBluetoothDeviceClass", sizeof(AstalBluetoothDeviceClass), alignof(AstalBluetoothDeviceClass));
    return 0;
}
