// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir/gir-files
// DO NOT EDIT

mod output;
pub use self::output::Output;

mod river;
pub use self::river::River;

pub mod builders {
    pub use super::output::OutputBuilder;
}
