// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir/gir-files
// DO NOT EDIT

use glib::translate::{FromGlibPtrNone, Uninitialized};

use crate::ffi;

glib::wrapper! {
    #[derive(Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
    pub struct Score(Boxed<ffi::AstalAppsScore>);

    match fn {
        copy => |ptr| glib::gobject_ffi::g_boxed_copy(ffi::astal_apps_score_get_type(), ptr as *mut _) as *mut ffi::AstalAppsScore,
        free => |ptr| glib::gobject_ffi::g_boxed_free(ffi::astal_apps_score_get_type(), ptr as *mut _),
        type_ => || ffi::astal_apps_score_get_type(),
    }
}

impl Uninitialized for Score {
    #[inline]
    unsafe fn uninitialized() -> Self {
        Score::from_glib_none(std::ptr::null_mut())
    }
}
