[options]
library = "AstalBluetooth"
version = "0.1"
min_cfg_version = "0.1"
target_path = "."
girs_directories = ["../../gir/gir-files"]
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = []

manual = ["Gio.AsyncReadyCallback", "Gio.AsyncResult"]

[[object]]
name = "AstalBluetooth.Device"
status = "generate"
generate_builder = true

[[object]]
name = "AstalBluetooth.Adapter"
status = "generate"
generate_builder = true

[[object]]
name = "AstalBluetooth.Bluetooth"
status = "generate"
generate_builder = true
