// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir/gir-files
// DO NOT EDIT

use crate::{ffi};
use glib::{GStr};

#[doc(alias = "ASTAL_IO_VERSION")]
pub static VERSION: &GStr = unsafe{GStr::from_utf8_with_nul_unchecked(ffi::ASTAL_IO_VERSION)};
