// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../gir/gir-files
// DO NOT EDIT

mod power_profiles;
pub use self::power_profiles::PowerProfiles;

mod hold;
pub use self::hold::Hold;

mod profile;
pub use self::profile::Profile;

pub mod traits {
    pub use super::power_profiles::PowerProfilesExt;
}
pub mod builders {
    pub use super::power_profiles::PowerProfilesBuilder;
}
