// Generated by gir (https://github.com/gtk-rs/gir @ 26e721588f2f)
// from ../../gir/gir-files (@ e02639f55a90)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "AstalBatteryBatteryLevel", sizeof(AstalBatteryBatteryLevel), alignof(AstalBatteryBatteryLevel));
    printf("%s;%zu;%zu\n", "AstalBatteryDevice", sizeof(AstalBatteryDevice), alignof(AstalBatteryDevice));
    printf("%s;%zu;%zu\n", "AstalBatteryDeviceClass", sizeof(AstalBatteryDeviceClass), alignof(AstalBatteryDeviceClass));
    printf("%s;%zu;%zu\n", "AstalBatteryState", sizeof(AstalBatteryState), alignof(AstalBatteryState));
    printf("%s;%zu;%zu\n", "AstalBatteryTechnology", sizeof(AstalBatteryTechnology), alignof(AstalBatteryTechnology));
    printf("%s;%zu;%zu\n", "AstalBatteryType", sizeof(AstalBatteryType), alignof(AstalBatteryType));
    printf("%s;%zu;%zu\n", "AstalBatteryUPower", sizeof(AstalBatteryUPower), alignof(AstalBatteryUPower));
    printf("%s;%zu;%zu\n", "AstalBatteryUPowerClass", sizeof(AstalBatteryUPowerClass), alignof(AstalBatteryUPowerClass));
    printf("%s;%zu;%zu\n", "AstalBatteryWarningLevel", sizeof(AstalBatteryWarningLevel), alignof(AstalBatteryWarningLevel));
    return 0;
}
